services:
  db:
    image: postgres:18
    container_name: postgres-dev
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "tack" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  postgres_data:
